name: Lint, tests and build

on:
  push:
    branches-ignore: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.x"

      - name: Deno check
        run: deno check

      - name: Deno lint
        run: deno lint

      - name: Deno fmt (check)
        run: deno fmt --check

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.x"

      - name: Tests
        run: deno test -A

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.x"

      - name: Compile
        run: deno task compile:all
